(function(){
"use strict";
var $=function(id){return document.getElementById(id)},N=function(v){v=Number(v);return isFinite(v)?v:0},E=function(v){return fmtEUR(N(v))},R=function(v){return fmtINR(N(v))};
var esc=function(s){return String(s==null?"":s).replace(/[&<>"]/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]})};
var uid=function(){return"v6_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)};
function save6(m){localStorage.setItem("virajFinance",JSON.stringify(data));if(typeof toast==="function"&&m)toast(m)}
function ensure(){data.transactions=data.transactions||[];data.accounts=data.accounts||[];data.goals=data.goals||[];data.networth=data.networth||[];data.settings=data.settings||{};data.settings.fxEurInr=N(data.settings.fxEurInr)||100;data.recurring=data.recurring||[];data.reconciliations=data.reconciliations||[];data.networthHistory=data.networthHistory||[];data.monthClose=data.monthClose||{};data.scenarios=data.scenarios||[];data.receipts=data.receipts||[];data.csvImports=data.csvImports||[];data.creditCard=data.creditCard||{balance:0,limit:0,statementDate:"",dueDate:"",minPayment:0}}
ensure();
var css=document.createElement("style");css.textContent=".v6g{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:15px}.v6g2{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:15px}.v6t{background:#fff;border:1px solid var(--line);border-radius:15px;padding:15px}.v6n{font-size:26px;font-weight:950;margin-top:4px}.v6s{font-size:12px;color:var(--muted);margin-top:4px}.v6bar{height:9px;background:#e5e7eb;border-radius:99px;overflow:hidden}.v6bar span{display:block;height:100%;background:linear-gradient(90deg,#4f46e5,#7c3aed)}.v6a{padding:11px;border-radius:11px;border:1px solid #e5e7eb;margin:7px 0}.v6a.good{background:#f0fdf4;border-color:#bbf7d0}.v6a.warn{background:#fffbeb;border-color:#fde68a}.v6a.bad{background:#fff1f2;border-color:#fecaca}.v6chart{height:210px;display:flex;align-items:end;gap:8px;padding:12px}.v6col{flex:1;text-align:center;font-size:9px}.v6col i{display:block;background:linear-gradient(#7c3aed,#4f46e5);border-radius:6px 6px 2px 2px;min-height:2px}.v6col b{display:block;font-size:10px}.v6sticky{position:fixed;right:20px;bottom:20px;z-index:40;border:0;border-radius:999px;padding:13px 17px;background:#4f46e5;color:#fff;font-weight:900;box-shadow:0 12px 30px #0003}@media(max-width:900px){.v6g,.v6g2{grid-template-columns:1fr 1fr}}@media(max-width:650px){.v6g,.v6g2{grid-template-columns:1fr 1fr}.v6n{font-size:21px}.v6sticky{right:12px;bottom:82px}}";document.head.appendChild(css);
function sec(id,title,sub,html){if($(id))return;var s=document.createElement("section");s.id=id;s.className="view";s.innerHTML='<div class="card hero"><div class="eyebrow" style="color:#c7d2fe">Advanced Finance Centre</div><h2>'+title+'</h2><p class="muted">'+sub+'</p></div>'+html;document.querySelector("main").appendChild(s)}
sec("health","Financial Health","Transparent planning indicators from your stored data.",'<div id="v6Health" class="v6g"></div><div class="card" style="margin-top:15px" id="v6HealthDetail"></div>');
sec("cashflow","Cash Flow Centre","Current cash, commitments, reserve and safe-to-spend.",'<div id="v6Cash" class="v6g"></div><div class="card" style="margin-top:15px"><h3>Purchase calculator</h3><div class="form"><div><label>Purchase €</label><input id="v6Buy" type="number" step=".01"></div><div><label>Required reserve €</label><input id="v6Res" type="number" value="1000" step=".01"></div></div><button class="primary" style="margin-top:10px" onclick="v6Afford()">Check</button><div id="v6Afford" style="margin-top:10px"></div></div><div class="card" style="margin-top:15px"><h3>12-month cash-flow estimate</h3><div id="v6CashChart" class="v6chart"></div></div>');
sec("recurring","Recurring Payments","Monthly obligations, savings and subscriptions.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Name</label><input id="v6rName"></div><div><label>Amount</label><input id="v6rAmt" type="number" step=".01"></div><div><label>Currency</label><select id="v6rCur"><option>EUR</option><option>INR</option></select></div><div><label>Day</label><input id="v6rDay" type="number" min="1" max="28" value="1"></div><div><label>Category</label><input id="v6rCat"></div><div><label>Account</label><select id="v6rAcc"></select></div></div><button class="primary" style="margin-top:10px" onclick="v6AddRecurring()">+ Add</button></div><div class="card" style="margin-top:15px" id="v6Recurring"></div>');
sec("reconcile","Account Reconciliation","Compare recorded balances with real balances.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Account</label><select id="v6recAcc"></select></div><div><label>Actual balance</label><input id="v6recActual" type="number" step=".01"></div><div><label>Date</label><input id="v6recDate" type="date"></div></div><button class="primary" style="margin-top:10px" onclick="v6Reconcile()">Reconcile</button></div><div class="card" style="margin-top:15px" id="v6Rec"></div>');
sec("analytics","Spending Analytics","Category and merchant analysis from monthly data and transactions.",'<div id="v6Analytics" class="v6g2"></div><div class="card" style="margin-top:15px" id="v6Analytics2"></div>');
sec("scenarios","Scenario Simulator","Change assumptions without changing real financial data.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Income €</label><input id="v6si" type="number"></div><div><label>Spend €</label><input id="v6ss" type="number"></div><div><label>AIB saving €</label><input id="v6sa" type="number" value="100"></div><div><label>Starting cash €</label><input id="v6sc" type="number"></div><div><label>Months</label><input id="v6sm" type="number" value="12"></div><div><label>Loan payment ₹</label><input id="v6sl" type="number" value="100000"></div></div><button class="primary" style="margin-top:10px" onclick="v6Scenario()">Run</button></div><div class="card" style="margin-top:15px" id="v6Scenario"></div>');
sec("homeplan","Mumbai Home Planner","Planning model for the ₹2 Cr home goal.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Property price ₹</label><input id="v6hp" type="number" value="20000000"></div><div><label>Down payment %</label><input id="v6hd" type="number" value="20"></div><div><label>Purchase costs %</label><input id="v6hc" type="number" value="8"></div><div><label>Existing fund ₹</label><input id="v6hf" type="number" value="0"></div><div><label>Target date</label><input id="v6hdate" type="date" value="2030-12-31"></div><div><label>Illustrative rate %</label><input id="v6hr" type="number" value="8" step=".1"></div><div><label>Loan years</label><input id="v6ht" type="number" value="20"></div></div><button class="primary" style="margin-top:10px" onclick="v6Home()">Calculate</button></div><div class="card" style="margin-top:15px" id="v6Home"></div>');
sec("loanlab","Education Loan Lab","Compare repayment plans using the app's current planning convention.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Opening ₹</label><input id="v6lo" type="number"></div><div><label>Monthly rate %</label><input id="v6lr" type="number" step=".001"></div><div><label>First payment</label><input id="v6ld" type="date"></div></div><button class="primary" style="margin-top:10px" onclick="v6LoanLab()">Compare ₹1L–₹2L</button></div><div class="card" style="margin-top:15px" id="v6LoanLab"></div>');
sec("history","Net Worth History","Capture snapshots and compare your financial position over time.",'<div class="card" style="margin-top:15px"><button class="primary" onclick="v6Snapshot()">Capture snapshot</button><div id="v6History" style="margin-top:12px"></div></div>');
sec("close","Monthly Close","Freeze a monthly review summary and reopen it when necessary.",'<div class="card" style="margin-top:15px"><div class="form"><div><label>Month</label><input id="v6cm" type="month"></div></div><button class="primary" style="margin-top:10px" onclick="v6Close()">Close month</button> <button onclick="v6Reopen()">Reopen</button></div><div class="card" style="margin-top:15px" id="v6Closed"></div>');
sec("alerts","Smart Alerts","Rule-based warnings based on current stored information.",'<div class="card" style="margin-top:15px" id="v6Alerts"></div>');
sec("import","Import & Export","CSV transactions and receipt capture.",'<div class="v6g2" style="margin-top:15px"><div class="card"><h3>CSV import</h3><p class="v6s">Columns: date, description, amount, currency, type, category, account.</p><input id="v6csv" type="file" accept=".csv"><button class="primary" style="margin-top:10px" onclick="v6CSV()">Import</button><div id="v6csvmsg"></div></div><div class="card"><h3>Receipt capture</h3><input id="v6receipt" type="file" accept="image/*" capture="environment" onchange="v6Receipt(event)"><div id="v6rp" class="v6s">Photo is kept locally with the receipt record.</div><div class="form" style="margin-top:10px"><div><label>Merchant</label><input id="v6rm"></div><div><label>Total €</label><input id="v6rt" type="number" step=".01"></div></div><button class="primary" style="margin-top:10px" onclick="v6SaveReceipt()">Save record</button></div></div>');
sec("versions","Backup Versions","Local snapshots plus optional timestamped Google Drive versions.",'<div class="card" style="margin-top:15px"><button class="primary" onclick="v6Version()">Save local version</button> <button onclick="v6DriveVersion()">Create Drive version</button><div id="v6Versions" style="margin-top:12px"></div></div>');
var nav=document.querySelector(".nav");var items=[["dashboard","📊 Dashboard"],["health","❤️ Health"],["cashflow","💶 Cash Flow"],["transactions","💳 Transactions"],["recurring","🔄 Recurring"],["monthly","📅 Monthly"],["grocery","🛒 Grocery"],["india","🇮🇳 India"],["misc","🧾 Misc"],["accounts","🏦 Accounts"],["reconcile","✓ Reconcile"],["goals","🎯 Goals"],["loan","🎓 Education Loan"],["loanlab","🧮 Loan Lab"],["networth","📈 Net Worth"],["history","📈 NW History"],["analytics","📊 Analytics"],["reports","📑 Reports"],["planning","🧭 Planning"],["scenarios","🔮 Scenarios"],["homeplan","🏠 Mumbai Home"],["alerts","🔔 Alerts"],["close","📆 Monthly Close"],["import","📥 Import/Export"],["versions","☁️ Versions"],["settings","⚙️ Settings"]];nav.innerHTML=items.map(function(x){return'<button data-v6="'+x[0]+'">'+x[1]+"</button>"}).join("");nav.querySelectorAll("button").forEach(function(b){b.onclick=function(){show6(b.dataset.v6,b)}});var oldShow=window.show;
function show6(id,b){document.querySelectorAll(".view").forEach(function(x){x.classList.remove("on")});if($(id))$(id).classList.add("on");nav.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});if(b)b.classList.add("active");var names={dashboard:"Dashboard",health:"Financial Health",cashflow:"Cash Flow Centre",transactions:"Transactions",recurring:"Recurring Payments",monthly:"Monthly",grocery:"Grocery",india:"India",misc:"Misc",accounts:"Accounts",reconcile:"Reconciliation",goals:"Goals",loan:"Education Loan",loanlab:"Education Loan Lab",networth:"Net Worth",history:"Net Worth History",analytics:"Spending Analytics",reports:"Reports",planning:"Planning Centre",scenarios:"Scenario Simulator",homeplan:"Mumbai Home Planner",alerts:"Smart Alerts",close:"Monthly Close",import:"Import & Export",versions:"Backup Versions",settings:"Settings"};if($("title"))$("title").textContent=names[id]||id;if(id==="monthly"&&typeof monthly==="function")monthly();if(id==="loan"&&typeof calcLoan==="function")calcLoan();render6(id)}
window.show=show6;
function spendable(){return data.accounts.filter(function(a){return a.currency==="EUR"&&a.includeInSafeSpend!==false&&a.type!=="Credit Card"}).reduce(function(s,a){return s+N(a.balance)},0)}
function avgSpend(){var ks=Object.keys(data.months).sort().slice(-3),s=0,c=0;ks.forEach(function(k){s+=Object.values(data.months[k].actual||{}).reduce(function(a,b){return a+N(b)},0);c++});return c?s/c:0}
function recurringEUR(){return data.recurring.filter(function(x){return x.currency==="EUR"}).reduce(function(s,x){return s+N(x.amount)},0)}
function nw(){var e=0,i=0;(data.accounts||[]).forEach(function(a){if(a.currency==="EUR")e+=N(a.balance);else i+=N(a.balance)});(data.networth||[]).forEach(function(x){if(x.currency==="EUR")e+=x.kind==="asset"?N(x.amount):-N(x.amount);else i+=x.kind==="asset"?N(x.amount):-N(x.amount)});if(data.loan)i-=N(data.loan.opening);return{e:e,i:i,fx:N(data.settings.fxEurInr)||100}}
function health(){var m=Object.values(data.months).slice(-3),inc=m.reduce(function(s,x){return s+N(x.income)},0),sp=m.reduce(function(s,x){return s+Object.values(x.actual||{}).reduce(function(a,b){return a+N(b)},0)},0),rate=inc?Math.max(0,(inc-sp)/inc):0,cc=data.creditCard||{},util=cc.limit?cc.balance/cc.limit:0,ef=data.goals.find(function(g){return g.name==="Emergency Fund"}),efp=ef&&ef.target?Math.min(1,N(ef.current)/N(ef.target)):0;return Math.round(Math.min(100,25*rate+20*Math.min(1,spendable()/5000)+20*(1-Math.min(1,util))+20*efp+15*(data.loan?0.6:1)))}
function renderHealth(){var h=health(),x=nw(),cc=data.creditCard||{},ef=data.goals.find(function(g){return g.name==="Emergency Fund"}),util=cc.limit?cc.balance/cc.limit*100:0;$("v6Health").innerHTML='<div class="v6t"><div class="eyebrow">Health score</div><div class="v6n">'+h+'/100</div><div class="v6bar"><span style="width:'+h+'%"></span></div><div class="v6s">Planning indicator, not a credit score.</div></div><div class="v6t"><div class="eyebrow">Spendable cash</div><div class="v6n">'+E(spendable())+'</div><div class="v6s">Excludes AIB Savings and cards.</div></div><div class="v6t"><div class="eyebrow">EUR net worth</div><div class="v6n">'+E(x.e)+'</div><div class="v6s">INR: '+R(x.i)+'</div></div><div class="v6t"><div class="eyebrow">Card utilisation</div><div class="v6n">'+(cc.limit?util.toFixed(0)+"%":"—")+'</div><div class="v6s">Emergency fund: '+(ef&&ef.target?(N(ef.current)/N(ef.target)*100).toFixed(0)+"%":"not configured")+'</div></div>';$("v6HealthDetail").innerHTML="<h3>Health components</h3><table class='v5table'><tr><th>Metric</th><th>Current</th></tr><tr><td>Recent average spending</td><td>"+E(avgSpend())+"</td></tr><tr><td>Recurring EUR</td><td>"+E(recurringEUR())+"</td></tr><tr><td>Education loan</td><td>"+R(data.loan?data.loan.opening:0)+"</td></tr><tr><td>FX planning rate</td><td>₹"+N(data.settings.fxEurInr).toFixed(2)+" / €1</td></tr></table>"}
function renderCash(){var safe=spendable()-recurringEUR()-1000,inc=N(Object.values(data.months).slice(-1)[0]?.income);$("v6Cash").innerHTML='<div class="v6t"><div class="eyebrow">Spendable now</div><div class="v6n">'+E(spendable())+'</div></div><div class="v6t"><div class="eyebrow">Recurring</div><div class="v6n">'+E(recurringEUR())+'</div></div><div class="v6t"><div class="eyebrow">Reserve</div><div class="v6n">€1,000</div></div><div class="v6t"><div class="eyebrow">Safe to spend</div><div class="v6n '+(safe>=0?"v6ok":"v6bad")+'">'+E(safe)+'</div></div>';var bal=spendable(),sp=avgSpend(),r=recurringEUR(),arr=[];for(var i=0;i<12;i++){bal+=inc-sp-r;arr.push(Math.max(0,bal))}var mx=Math.max.apply(null,arr.concat([1]));$("v6CashChart").innerHTML=arr.map(function(v,i){return'<div class="v6col"><i style="height:'+Math.max(3,v/mx*170)+'px"></i><b>'+E(v)+'</b><span>M'+(i+1)+"</span></div>"}).join("")}
window.v6Afford=function(){var c=N($("v6Buy").value),r=N($("v6Res").value),a=spendable()-c;$("v6Afford").innerHTML=c<=0?'<div class="v6a warn">Enter a purchase amount.</div>':a>=r?'<div class="v6a good">After the purchase, '+E(a)+' remains above the '+E(r)+' reserve.</div>':'<div class="v6a bad">This purchase would take spendable cash below the reserve.</div>'};
function renderRecurring(){var s=$("v6rAcc");s.innerHTML='<option value="">Unassigned</option>'+data.accounts.map(function(a){return'<option value="'+a.id+'">'+esc(a.name)+" · "+a.currency+"</option>"}).join("");var rows=data.recurring.map(function(x){return "<tr><td>"+esc(x.name)+"</td><td>"+(x.currency==="INR"?R(x.amount):E(x.amount))+"</td><td>"+x.day+"</td><td>"+esc(x.category)+"</td><td><button class='danger' onclick='v6DelRecurring(\""+x.id+"\")'>Delete</button></td></tr>"}).join("");$("v6Recurring").innerHTML=rows?'<table class="v5table"><tr><th>Name</th><th>Amount</th><th>Day</th><th>Category</th><th></th></tr>'+rows+"</table>":"<div class='v6a'>No recurring payments yet.</div>"}
window.v6AddRecurring=function(){var name=$("v6rName").value.trim(),amt=N($("v6rAmt").value);if(!name||amt<=0)return alert("Enter name and amount.");data.recurring.push({id:uid(),name:name,amount:amt,currency:$("v6rCur").value,day:Math.min(28,Math.max(1,parseInt($("v6rDay").value)||1)),category:$("v6rCat").value.trim()||"Other",accountId:$("v6rAcc").value});save6("Recurring saved");renderRecurring();renderCash()};
window.v6DelRecurring=function(id){data.recurring=data.recurring.filter(function(x){return x.id!==id});save6();renderRecurring();renderCash()};
function renderRec(){var s=$("v6recAcc");s.innerHTML=data.accounts.map(function(a){return'<option value="'+a.id+'">'+esc(a.name)+" · "+a.currency+"</option>"}).join("");var rows=data.reconciliations.slice().reverse().map(function(x){return"<tr><td>"+x.date+"</td><td>"+esc(x.account)+"</td><td>"+E(x.app)+"</td><td>"+E(x.actual)+"</td><td>"+E(x.diff)+"</td></tr>"}).join("");$("v6Rec").innerHTML=rows?'<table class="v5table"><tr><th>Date</th><th>Account</th><th>App</th><th>Actual</th><th>Difference</th></tr>'+rows+"</table>":"<div class='v6a'>No reconciliation history.</div>"}
window.v6Reconcile=function(){var a=data.accounts.find(function(x){return x.id===$("v6recAcc").value});if(!a)return;var actual=N($("v6recActual").value),d=$("v6recDate").value||new Date().toISOString().slice(0,10);data.reconciliations.push({date:d,account:a.name,app:N(a.balance),actual:actual,diff:actual-N(a.balance)});save6("Reconciliation saved");renderRec();renderAlerts()};
function renderAnalytics(){var c={},m={};Object.keys(data.months).slice(-3).forEach(function(k){Object.keys(data.months[k].actual||{}).forEach(function(z){c[z]=(c[z]||0)+N(data.months[k].actual[z])})});data.transactions.forEach(function(t){if(t.type==="expense"&&t.currency==="EUR"){c[t.category||"Other"]=(c[t.category||"Other"]||0)+N(t.amount);m[t.description||"Unknown"]=(m[t.description||"Unknown"]||0)+N(t.amount)}});var cr=Object.entries(c).sort(function(a,b){return b[1]-a[1]}).map(function(x){return"<tr><td>"+esc(x[0])+"</td><td>"+E(x[1])+"</td></tr>"}).join(""),mr=Object.entries(m).sort(function(a,b){return b[1]-a[1]}).slice(0,10).map(function(x){return"<tr><td>"+esc(x[0])+"</td><td>"+E(x[1])+"</td></tr>"}).join("");$("v6Analytics").innerHTML='<div class="card"><h3>Spend by category</h3><table class="v5table"><tr><th>Category</th><th>Amount</th></tr>'+cr+"</table></div><div class='card'><h3>Top transaction descriptions</h3><table class='v5table'><tr><th>Description</th><th>Amount</th></tr>"+mr+"</table></div>";$("v6Analytics2").innerHTML="<h3>Fixed vs variable</h3><div class='v6g'><div class='v6t'><div class='eyebrow'>Fixed recurring</div><div class='v6n'>"+E(recurringEUR())+"</div></div><div class='v6t'><div class='eyebrow'>Recent tracked spend</div><div class='v6n'>"+E(avgSpend())+"</div></div></div>"}
function renderAlerts(){var a=[],cc=data.creditCard||{},u=cc.limit?cc.balance/cc.limit:0;if(u>.8)a.push(["bad","Credit card utilisation is above 80%."]);else if(u>.5)a.push(["warn","Credit card utilisation is above 50%."]);var safe=spendable()-recurringEUR()-1000;if(safe<0)a.push(["bad","Current recurring commitments plus the €1,000 reserve exceed spendable cash."]);var ef=data.goals.find(function(g){return g.name==="Emergency Fund"});if(ef&&ef.target&&N(ef.current)<N(ef.target))a.push(["warn","Emergency Fund is "+(N(ef.current)/N(ef.target)*100).toFixed(0)+"% funded."]);if(!a.length)a.push(["good","No major rule-based alerts detected."]);$("v6Alerts").innerHTML=a.map(function(x){return'<div class="v6a '+x[0]+'">'+esc(x[1])+"</div>"}).join("")}
function defaults(){var m=Object.values(data.months).slice(-1)[0]||{};$("v6si").value=N(m.income);$("v6ss").value=avgSpend();$("v6sc").value=spendable()}
window.v6Scenario=function(){var i=N($("v6si").value),s=N($("v6ss").value),a=N($("v6sa").value),b=N($("v6sc").value),mo=Math.max(1,Math.min(120,parseInt($("v6sm").value)||12)),rows="";for(var k=1;k<=Math.min(12,mo);k++){b+=i-s-a;rows+="<tr><td>"+k+"</td><td>"+E(b)+"</td></tr>"}data.scenarios.push({date:new Date().toISOString(),income:i,spend:s,aib:a,loan:N($("v6sl").value),months:mo});save6("Scenario saved");$("v6Scenario").innerHTML='<div class="v6g"><div class="v6t"><div class="eyebrow">Monthly surplus</div><div class="v6n">'+E(i-s-a)+'</div></div><div class="v6t"><div class="eyebrow">Ending cash</div><div class="v6n">'+E(b)+'</div></div><div class="v6t"><div class="eyebrow">Loan payment</div><div class="v6n">'+R($("v6sl").value)+'</div></div></div><table class="v5table"><tr><th>Month</th><th>Ending cash</th></tr>'+rows+"</table>"};
function emi(p,r,n){r=r/1200;return r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n}
window.v6Home=function(){var p=N($("v6hp").value),d=N($("v6hd").value)/100,c=N($("v6hc").value)/100,f=N($("v6hf").value),price=p*d,extra=p*c,need=Math.max(0,price+extra-f),target=new Date($("v6hdate").value+"T00:00:00"),now=new Date(),mo=Math.max(1,(target.getFullYear()-now.getFullYear())*12+target.getMonth()-now.getMonth()),loan=p-price,m=emi(loan,N($("v6hr").value),Math.max(1,N($("v6ht").value))*12);$("v6Home").innerHTML='<div class="v6g"><div class="v6t"><div class="eyebrow">Down payment</div><div class="v6n">'+R(price)+'</div></div><div class="v6t"><div class="eyebrow">Purchase costs</div><div class="v6n">'+R(extra)+'</div></div><div class="v6t"><div class="eyebrow">Cash required</div><div class="v6n">'+R(need)+'</div></div><div class="v6t"><div class="eyebrow">Illustrative EMI</div><div class="v6n">'+R(m)+'</div></div></div><div class="v6a good">Simple monthly accumulation required: <b>'+R(need/mo)+'/month</b> for about '+mo+' months. This excludes returns and future property-price changes.</div>'}
function loan(open,rate,pay,start){var b=open,interest=0,n=0,d=new Date(start+"T00:00:00");while(b>.01&&n<240){var it=n===0?17967:b*rate/100,pa=Math.min(pay,b+it);b=Math.max(0,b-(pa-it));interest+=it;n++;d.setMonth(d.getMonth()+1)}return{n:n,i:interest,date:new Date(d.getTime()-86400000)}}
window.v6LoanLab=function(){var o=N($("v6lo").value),r=N($("v6lr").value),d=$("v6ld").value||"2026-10-11",rows=[100000,125000,150000,175000,200000].map(function(p){var x=loan(o,r,p,d);return"<tr><td>"+R(p)+"</td><td>"+x.n+"</td><td>"+R(x.i)+"</td><td>"+x.date.toLocaleDateString("en-IE",{month:"short",year:"numeric"})+"</td></tr>"}).join("");$("v6LoanLab").innerHTML='<table class="v5table"><tr><th>Payment</th><th>Months</th><th>Interest</th><th>Payoff</th></tr>'+rows+"</table><div class='v6s'>Planning model only; not a lender payoff quote.</div>"};
window.v6Snapshot=function(){var x=nw();data.networthHistory.push({date:new Date().toISOString().slice(0,10),eur:x.e,inr:x.i,fx:x.fx});save6("Net worth snapshot saved");renderHistory()};function renderHistory(){var r=data.networthHistory.slice().reverse().map(function(x){return"<tr><td>"+x.date+"</td><td>"+E(x.eur)+"</td><td>"+R(x.inr)+"</td><td>"+N(x.fx).toFixed(2)+"</td></tr>"}).join("");$("v6History").innerHTML=r?'<table class="v5table"><tr><th>Date</th><th>EUR</th><th>INR</th><th>FX</th></tr>'+r+"</table>":"<div class='v6a'>No snapshots yet.</div>"}
window.v6Close=function(){var k=$("v6cm").value||new Date().toISOString().slice(0,7),m=data.months[k];if(!m)return alert("Month not found.");var s=Object.values(m.actual||{}).reduce(function(a,b){return a+N(b)},0);data.monthClose[k]={date:new Date().toISOString(),income:N(m.income),spend:s,left:N(m.income)-s};save6("Month closed");renderClosed()};window.v6Reopen=function(){var k=$("v6cm").value;if(k){delete data.monthClose[k];save6("Month reopened");renderClosed()}};function renderClosed(){var r=Object.entries(data.monthClose).sort().reverse().map(function(x){return"<tr><td>"+x[0]+"</td><td>"+E(x[1].income)+"</td><td>"+E(x[1].spend)+"</td><td>"+E(x[1].left)+"</td></tr>"}).join("");$("v6Closed").innerHTML=r?'<table class="v5table"><tr><th>Month</th><th>Income</th><th>Spend</th><th>Left</th></tr>'+r+"</table>":"<div class='v6a'>No closed months.</div>"}
window.v6CSV=function(){var f=$("v6csv").files[0];if(!f)return alert("Choose a CSV.");var r=new FileReader();r.onload=function(){var lines=r.result.split(/\r?\n/).filter(Boolean),h=lines.shift().split(",").map(function(x){return x.trim().toLowerCase()}),c=0;lines.forEach(function(line){var v=line.split(","),o={};h.forEach(function(k,i){o[k]=(v[i]||"").trim().replace(/^"|"$/g,"")});var amt=N(o.amount);if(!o.date||!amt)return;var a=data.accounts.find(function(x){return x.name.toLowerCase()===(o.account||"").toLowerCase()});data.transactions.push({id:uid(),date:o.date,description:o.description||"Imported",amount:Math.abs(amt),currency:o.currency==="INR"?"INR":"EUR",type:o.type==="income"?"income":"expense",category:o.category||"Imported",accountId:a?a.id:"",notes:"CSV import"});c++});data.csvImports.push({date:new Date().toISOString(),file:f.name,count:c});save6(c+" transactions imported");$("v6csvmsg").innerHTML='<div class="v6a good">Imported '+c+" rows.</div>";renderAnalytics()};r.readAsText(f)};
window.v6Receipt=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){$("v6rp").innerHTML='<img src="'+r.result+'" style="max-width:100%;max-height:170px;border-radius:10px"><div class="v6s">Photo captured. Enter merchant and total, then save.</div>';window._v6img=r.result};r.readAsDataURL(f)};window.v6SaveReceipt=function(){var m=$("v6rm").value.trim(),t=N($("v6rt").value);if(!m||!t)return alert("Enter merchant and total.");data.receipts.push({date:new Date().toISOString().slice(0,10),merchant:m,total:t,image:window._v6img||""});save6("Receipt saved");alert("Receipt record saved. Automatic OCR is not enabled in this build; the image and manual total are preserved.");};
window.v6Version=function(){var v=JSON.parse(localStorage.getItem("virajFinanceVersions")||"[]");v.push({date:new Date().toISOString(),data:data});while(v.length>10)v.shift();localStorage.setItem("virajFinanceVersions",JSON.stringify(v));renderVersions();save6("Local version saved")};
window.v6DriveVersion=async function(){if(typeof getDriveToken!=="function")return alert("Connect Google Drive in Settings first.");try{var token=await getDriveToken();if(!token)return;var payload=JSON.stringify({app:"Viraj Personal Finance Centre",version:6,savedAt:new Date().toISOString(),data:data},null,2),name="Viraj_Finance_Version_"+new Date().toISOString().replace(/[:.]/g,"-")+".json",meta={name:name,mimeType:"application/json"},b="----virajv6"+Date.now(),body="--"+b+"\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n"+JSON.stringify(meta)+"\r\n--"+b+"\r\nContent-Type: application/json\r\n\r\n"+payload+"\r\n--"+b+"--";var res=await driveRequest("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart",{method:"POST",headers:{"Content-Type":"multipart/related; boundary="+b},body:body});if(!res.ok)throw new Error("Drive version failed ("+res.status+").");toast("Drive version created")}catch(e){alert(e.message)}};
function renderVersions(){var v=JSON.parse(localStorage.getItem("virajFinanceVersions")||"[]").slice().reverse();$("v6Versions").innerHTML=v.length?v.map(function(x,i){return'<div class="v6a"><b>'+new Date(x.date).toLocaleString("en-IE")+'</b><button style="float:right" onclick="v6Restore('+i+')">Restore</button></div>'}).join(""):"<div class='v6a'>No local versions.</div>"}window.v6Restore=function(i){var v=JSON.parse(localStorage.getItem("virajFinanceVersions")||"[]").slice().reverse();if(!v[i]||!confirm("Restore this version?"))return;data=v[i].data;save6("Version restored");location.reload()};
function render6(id){ensure();if(id==="health")renderHealth();if(id==="cashflow")renderCash();if(id==="recurring")renderRecurring();if(id==="reconcile")renderRec();if(id==="analytics")renderAnalytics();if(id==="scenarios"){defaults()}if(id==="homeplan")v6Home();if(id==="loanlab"){if(data.loan){$("v6lo").value=N(data.loan.opening);$("v6lr").value=N(data.loan.rate);$("v6ld").value=data.loan.start||"2026-10-11"}}if(id==="history")renderHistory();if(id==="close")renderClosed();if(id==="alerts")renderAlerts();if(id==="versions")renderVersions()}
function renderAll(){renderHealth();renderCash();renderRecurring();renderRec();renderAnalytics();renderAlerts();renderHistory();renderClosed();renderVersions()}
renderAll();
var q=document.createElement("button");q.className="v6sticky";q.textContent="＋ Quick expense";q.onclick=function(){var b=document.querySelector('[data-v6="transactions"]');show6("transactions",b);setTimeout(function(){if($("v5txAmount"))$("v5txAmount").focus()},60)};document.body.appendChild(q);
})();